pipeline{
  agent{
    docker{
    image 'python:2.1.16-slim'
}
}
  stages{
    stage('build'){
      steps{
        echo 'building vote app'
        dir('worker'){
        sh 'python compile'
}
}
}
    stage('test'){
      steps{
        echo 'running unit tests on vote app'
        dir('worker'){
        sh 'python test'
}
}
}

}
  post{
    always{
      echo 'the job is complete'
}
}
}
