pipeline{
  agent any

  tools{
    maven 'Maven 3.6.1'
}

  stages{
    stage('build') {
      when{
        changeset "**/worker/**"
      }

        steps {
            echo 'Compiling worker app'
            dir('worker'){
              sh 'mvn compile'
            }
        }
    }
    stage('test') {

    when{
        changeset "**/worker/**"
        }

        steps{
            echo 'Running'
            dir('worker'){
                sh 'mvn clean test'
            }
        }
    }


    stage('package') {
    when{
        changeset "**/worker/**"
    }
        steps{
            echo 'Packaging'
            dir('worker'){
                sh 'mvn package -DskipTests'
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }
    }
}
  post{
    always{
      echo 'Pipeline for worker is complete ,yes.!!.'
  }
  failure{
    slackSend(channel:"codechannel",message:"Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
  }
  success{
    slackSend(channel:"codechannel",message:"Build Success - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
  }




}

}
